### ISSUE TITLE
kitchen-cli: Materialize select

### ISSUE THREAD

**Issue by KoenLav** [perak/kitchen-templates#9]
Meteor Kitchen adds a new line as well as spaces line before and after every select option. This causes Materialize to generate every margin with a select option to the right.

I tried to fix this in the templates:
<option id="form-input-select-item" value="ITEM_VALUE">ITEM_TITLE</option>

But the new lines/spaces are still added, so this probably needs to be addressed in kitchen-cli.

**Comment by perak** [comment]
@KoenLav thanks, problem is html parser in kitchen-cli

**Comment by perak** [comment]
@KoenLav to save me from experimenting, can you please copy&paste invalid part of html generated by kitchen and manually fixed valid one?

**Comment by KoenLav** [comment]
`
					<option value="" disabled selected>
						Choose Bovenliggende categorie
					</option>
					{{#each categories}}
					<option value="{{_id}}" {{optionIsSelected ../category.parent_id _id}}>
						{{name}}
					</option>
`

`
<option value="" disabled selected>Choose Category</option>
{{#each categories}}
<option value="{{_id}}" {{optionIsSelected ../category.parent_id _id}}>{{name}}</option>
{{/each}}
`

**Comment by KoenLav** [comment]
https://jsfiddle.net/0Lhbdade/

**Comment by perak** [comment]
@KoenLav ah, now I understand. Fixed. Will be available in next version v0.9.58

**Comment by KoenLav** [comment]
Great, thanks!
